# Generated by Django 5.0.6 on 2024-06-17 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateReleaseBase',
            fields=[
                ('templatebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.templatebase')),
                ('author', models.CharField(max_length=255)),
                ('graph', models.ImageField(upload_to='')),
                ('release_date', models.DateField()),
                ('is_recommended', models.BooleanField()),
            ],
            bases=('core.templatebase',),
        ),
    ]
