name: Code quality checks
on: push

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Check code with ruff
        uses: chartboost/ruff-action@v1
        with:
          args: check
  poetry-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8
      - name: Check dependencies with poetry
        run:
          poetry update
          poetry checks